import http from "node:http";import crypto from "node:crypto";import {store} from "./store.js";import {validateJob,executeHttp,runWithRetry,nextRun} from "./runner.js";
const port=Number(process.env.PORT||3000),running=new Set();const json=(r,c,x)=>{r.writeHead(c,{"content-type":"application/json"});r.end(JSON.stringify(x))};const body=r=>new Promise((ok,no)=>{let s="";r.on("data",d=>s+=d);r.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})});
const prepare=j=>{j=validateJob(j);if(j.cron)j.nextRun=nextRun(j.cron).toISOString();return j};
async function run(job){if(running.has(job.id)&&job.denyOverlap!==false)throw Error("job already running");running.add(job.id);const id=crypto.randomUUID(),startedAt=new Date().toISOString();try{const result=await runWithRetry(()=>executeHttp(job),{maxRetries:job.maxRetries,backoffMs:job.retryBackoffSeconds*1000});store.log({id,jobId:job.id,status:"ok",startedAt,finishedAt:new Date().toISOString(),result});return {executionId:id,result}}catch(e){store.log({id,jobId:job.id,status:"error",startedAt,finishedAt:new Date().toISOString(),error:e.message});throw e}finally{running.delete(job.id)}}
setInterval(()=>{for(const j of store.list()){if(!j.enabled||!j.cron)continue;if(j.nextRun&&Date.parse(j.nextRun)<=Date.now()){j.nextRun=nextRun(j.cron).toISOString();store.put(j);run(j).catch(()=>{});}}},1000).unref();
http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://x"),p=u.pathname;if(req.method==="GET"&&p==="/health")return json(res,200,{ok:true,running:[...running]});if(req.method==="GET"&&p==="/jobs")return json(res,200,store.list());if(req.method==="GET"&&p==="/logs")return json(res,200,store.logs(u.searchParams.get("jobId")));if(req.method==="POST"&&p==="/jobs"){let j=prepare(await body(req));j={...j,id:j.id||crypto.randomUUID(),createdAt:new Date().toISOString()};return json(res,201,store.put(j));}
let m=p.match(/^\/jobs\/([^/]+)$/);if(m){const old=store.get(m[1]);if(!old)return json(res,404,{error:"not found"});if(req.method==="GET")return json(res,200,old);if(req.method==="DELETE"){store.del(m[1]);return json(res,200,{deleted:true,id:m[1]});}if(req.method==="PATCH"){const patch=await body(req),j=prepare({...old,...patch,id:old.id,createdAt:old.createdAt,updatedAt:new Date().toISOString()});return json(res,200,store.put(j));}}
m=p.match(/^\/jobs\/([^/]+)\/(enable|disable|run)$/);if(m){const j=store.get(m[1]);if(!j)return json(res,404,{error:"not found"});if(m[2]==="enable"||m[2]==="disable"){j.enabled=m[2]==="enable";if(j.enabled&&j.cron)j.nextRun=nextRun(j.cron).toISOString();return json(res,200,store.put(j));}return json(res,200,await run(j));}
m=p.match(/^\/webhooks\/([^/]+)$/);if(req.method==="POST"&&m){const j=store.get(m[1]);if(!j)return json(res,404,{error:"not found"});if(!j.enabled)return json(res,409,{error:"job disabled"});return json(res,200,await run({...j,body:await body(req)}));}
m=p.match(/^\/executions\/([^/]+)\/retry$/);if(req.method==="POST"&&m){const ex=store.execution(m[1]);if(!ex)return json(res,404,{error:"execution not found"});const j=store.get(ex.jobId);if(!j)return json(res,404,{error:"job not found"});return json(res,200,await run(j));}
return json(res,404,{error:"not found"});}catch(e){json(res,400,{error:e.message})}}).listen(port,()=>console.log("Automation Runner on :"+port));