import http from "node:http";import crypto from "node:crypto";import {store} from "./store.js";import {validateJob,executeHttp,runWithRetry,nextRun} from "./runner.js";import {authenticate,handleMcp} from "./mcp.js";
const port=Number(process.env.PORT||3000),running=new Set();const json=(r,c,x)=>{r.writeHead(c,{"content-type":"application/json"});r.end(JSON.stringify(x))};const body=r=>new Promise((ok,no)=>{let s="";r.on("data",d=>s+=d);r.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})});
const prepare=j=>{j=validateJob(j);if(j.cron)j.nextRun=nextRun(j.cron).toISOString();return j};
async function run(job){if(running.has(job.id)&&job.denyOverlap!==false)throw Error("job already running");running.add(job.id);const id=crypto.randomUUID(),startedAt=new Date().toISOString();try{const result=await runWithRetry(()=>executeHttp(job),{maxRetries:job.maxRetries,backoffMs:job.retryBackoffSeconds*1000});store.log({id,jobId:job.id,status:"ok",startedAt,finishedAt:new Date().toISOString(),result});return {executionId:id,result}}catch(e){store.log({id,jobId:job.id,status:"error",startedAt,finishedAt:new Date().toISOString(),error:e.message});throw e}finally{running.delete(job.id)}}
const getJob=id=>{const j=store.get(id);if(!j)throw Error("job not found");return j};const createJob=a=>{let j=prepare(a);j={...j,id:j.id||crypto.randomUUID(),createdAt:new Date().toISOString()};return store.put(j)};const updateJob=(id,a)=>{const old=getJob(id);const {id:_drop,...patch}=a;return store.put(prepare({...old,...patch,id:old.id,createdAt:old.createdAt,updatedAt:new Date().toISOString()}))};const setEnabled=(id,enabled)=>{const j=getJob(id);j.enabled=enabled;if(enabled&&j.cron)j.nextRun=nextRun(j.cron).toISOString();return store.put(j)};const retryExecution=id=>{const ex=store.execution(id);if(!ex)throw Error("execution not found");return run(getJob(ex.jobId))};const ctx={store,createJob,updateJob,runJob:id=>run(getJob(id)),setEnabled,retryExecution};
setInterval(()=>{for(const j of store.list()){if(!j.enabled||!j.cron)continue;if(j.nextRun&&Date.parse(j.nextRun)<=Date.now()){j.nextRun=nextRun(j.cron).toISOString();store.put(j);run(j).catch(()=>{});}}},1000).unref();
http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://x"),p=u.pathname;if(req.method==="GET"&&p==="/health")return json(res,200,{ok:true,running:[...running]});if(!authenticate(req.headers))return json(res,401,{error:"unauthorized"});if(req.method==="POST"&&p==="/mcp"){const response=await handleMcp(await body(req),ctx);if(response===null){res.writeHead(202);return res.end()}return json(res,200,response)}if(req.method==="GET"&&p==="/jobs")return json(res,200,store.list());if(req.method==="GET"&&p==="/logs")return json(res,200,store.logs(u.searchParams.get("jobId")));if(req.method==="POST"&&p==="/jobs")return json(res,201,createJob(await body(req)));
let m=p.match(/^\/jobs\/([^/]+)$/);if(m){if(req.method==="GET")return json(res,200,getJob(m[1]));if(req.method==="DELETE"){getJob(m[1]);store.del(m[1]);return json(res,200,{deleted:true,id:m[1]})}if(req.method==="PATCH")return json(res,200,updateJob(m[1],await body(req)));}
m=p.match(/^\/jobs\/([^/]+)\/(enable|disable|run)$/);if(m){if(m[2]==="enable"||m[2]==="disable")return json(res,200,setEnabled(m[1],m[2]==="enable"));return json(res,200,await run(getJob(m[1])))}
m=p.match(/^\/webhooks\/([^/]+)$/);if(req.method==="POST"&&m){const j=getJob(m[1]);if(!j.enabled)return json(res,409,{error:"job disabled"});return json(res,200,await run({...j,body:await body(req)}))}
m=p.match(/^\/executions\/([^/]+)\/retry$/);if(req.method==="POST"&&m)return json(res,200,await retryExecution(m[1]));return json(res,404,{error:"not found"});}catch(e){json(res,400,{error:e.message})}}).listen(port,()=>console.log("Automation Runner on :"+port));